name: Apply schema migrations

# 👉 Only run this workflow when a change is made to the main branch
on:
  push:
    branches:
      - master

jobs:
  apply_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & tooling
        run: |
          npm install
          npm install -g drizzle-orm drizzle-kit pg
      - name: Generate .env
        run: |
          touch .env
          echo DATABASE_URL={{secrets.DATABASE_URL}} >> .env
      - name: Apply migrations
        run: |
          drizzle-kit generate
          drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
